// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIh3ADEkz2UsqL872bKJNCtlDCpLGATc',
    appId: '1:532714324523:web:475393cf7d167900b4206e',
    messagingSenderId: '532714324523',
    projectId: 'noticar-39089',
    authDomain: 'noticar-39089.firebaseapp.com',
    storageBucket: 'noticar-39089.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjmeBwhCQOkPwP4mWdR3G1FnC5EtDPd84',
    appId: '1:532714324523:android:7c86d7e8502fd54ab4206e',
    messagingSenderId: '532714324523',
    projectId: 'noticar-39089',
    storageBucket: 'noticar-39089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_6E0ZTwU0J8-vQLVjmQ71fLQ2KMR1Pw',
    appId: '1:532714324523:ios:31072c618ea08c73b4206e',
    messagingSenderId: '532714324523',
    projectId: 'noticar-39089',
    storageBucket: 'noticar-39089.appspot.com',
    iosBundleId: 'com.example.notiAuto',
  );

}